// Loads data/vscode-catalog-data.json, generated by
// pipeline/auto_update_vscode_catalog.py. Deliberately separate from
// js/catalog-shared.js (the JetBrains pipeline's loader) -- different
// marketplace, different data shape, and kept out of the JetBrains
// parity checks in .github/workflows/update-catalog.yml. A page that
// doesn't call GapVSCode.ready simply never fetches this file.
(function () {
  'use strict';

  var ready = fetch('data/vscode-catalog-data.json', { credentials: 'same-origin' })
    .then(function (response) {
      if (!response.ok) throw new Error('VS Code catalog request failed: ' + response.status);
      return response.json();
    })
    .then(function (data) {
      if (!data || !Array.isArray(data.extensions)) throw new Error('VS Code catalog response is invalid');
      return data;
    });

  window.GapVSCode = { ready: ready };
})();
