#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Refresh the public VS Code extension catalog from the VS Code
Marketplace public gallery API.

Kept fully separate from ``auto_update_catalog.py`` (the JetBrains
pipeline): different marketplace, different API shape, and the
JetBrains file's generated output feeds parity checks (catalog JSON /
JSON-LD / no-script counts) in ``update-catalog.yml`` that must never
see these entries. The generated browser data is written to
``data/vscode-catalog-data.json``, loaded independently by the site.

Curated fields (displayName/pitch/niche/repo) live in
``pipeline/vscode_static_metadata.json`` and are not re-generated by
this script -- see that file's "_comment" for how to update them by
hand when an extension is added or its description changes.

Usage:
    python pipeline/auto_update_vscode_catalog.py
"""
import json
import os
import sys
import urllib.request
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_PATH = os.path.join(ROOT, "pipeline", "vscode_static_metadata.json")
DATA_PATH = os.path.join(ROOT, "data", "vscode-catalog-data.json")

PUBLISHER = "GapHunterLabs"
API_URL = "https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery"
UA = {
    "Accept": "application/json;api-version=3.0-preview.1",
    "Content-Type": "application/json",
    "User-Agent": "gap-hunter-auto-update/1.0",
}


def query_marketplace(names):
    """One batched request: each extension gets its own filter entry,
    each filter entry returns its own result set (parallel, same order
    as the input list) -- avoids 21 separate HTTP round-trips."""
    body = {
        "filters": [
            {
                "criteria": [{"filterType": 7, "value": f"{PUBLISHER}.{name}"}],
                "pageNumber": 1,
                "pageSize": 1,
                "sortBy": 0,
                "sortOrder": 0,
            }
            for name in names
        ],
        "flags": 914,  # IncludeVersions | IncludeStatistics | IncludeLatestVersionOnly (see MS Gallery API docs)
    }
    req = urllib.request.Request(
        API_URL, data=json.dumps(body).encode("utf-8"), headers=UA, method="POST"
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        payload = json.load(resp)
    return payload["results"]


def main():
    with open(STATIC_PATH, encoding="utf-8") as f:
        static = json.load(f)
    extensions_meta = static["extensions"]
    names = list(extensions_meta.keys())

    try:
        results = query_marketplace(names)
    except Exception as exc:  # network hiccup, marketplace outage, etc.
        print(f"[warn] VS Code Marketplace query failed: {exc}", file=sys.stderr)
        results = [{"extensions": []} for _ in names]

    extensions = []
    missing = []
    for name, result in zip(names, results):
        meta = extensions_meta[name]
        exts = result.get("extensions", [])
        if not exts:
            missing.append(name)
            continue
        e = exts[0]
        version = e["versions"][0] if e.get("versions") else {}
        stats = {s["statisticName"]: s["value"] for s in e.get("statistics", [])}
        extensions.append({
            "name": name,
            "displayName": meta["displayName"],
            "pitch": meta["pitch"],
            "niche": meta["niche"],
            "repo": meta["repo"],
            "githubUrl": f"https://github.com/GapHunterLabs/{meta['repo']}",
            "marketplaceUrl": f"https://marketplace.visualstudio.com/items?itemName={PUBLISHER}.{name}",
            "version": version.get("version"),
            "publishedDate": e.get("publishedDate"),
            "lastUpdated": e.get("lastUpdated"),
            "installs": int(stats.get("install", 0)),
            "rating": stats.get("averagerating"),
            "ratingCount": int(stats.get("ratingcount", 0)),
        })

    if missing:
        # Not an error: an extension can be mid-review (see the real
        # "suspicious content" hold documented for one entry) or simply
        # not uploaded yet. Log it, don't fail the run over it -- the
        # curated file is the source of truth for "exists in the
        # catalog"; the live query only adds metrics once it's public.
        print(f"[info] not live on the marketplace yet, skipped: {', '.join(missing)}", file=sys.stderr)

    extensions.sort(key=lambda x: x["displayName"])
    data = {
        "generatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        "totalExtensions": len(extensions),
        "totalInstalls": sum(x["installs"] for x in extensions),
        "pendingCount": len(missing),
        "extensions": extensions,
    }

    os.makedirs(os.path.dirname(DATA_PATH), exist_ok=True)
    with open(DATA_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"wrote {DATA_PATH}: {len(extensions)} live, {len(missing)} pending")


if __name__ == "__main__":
    main()
